### PR TITLE
Feature/search website

### PR DESCRIPTION
**Pull request by helloimela**
- Added search service
- Added correct styling on mobile and desktop
- Fix search logic
- Improve behavior when search is empty or when page is reloading
- Fix url on search list

How to test:
- Check UI design in Figma > Navigation > Header > Search Result
- Right now search is limited to only show 7 result (see carbon website search behavior).

Additional notes:
- Might improve search logic in the future: add indexing libraries from the content perspective.
- Right now indexing is done based on text search inside "Text" and "Lead Text" field in  the order of the data menu id inside content.json
- For a better search result, we should add tags on every pages. Should make it available from CMS data.

### CODE REVIEW

**Comment by niklasros** [comment]
The entire container for the search "button" could be clickable, but currently only the search icon is clickable.

**Comment by niklasros** [comment]
When search is expanded, it would be great if the text field is active so that the user can start writing directly instead of having to click it again.

**Comment by niklasros** [comment]
The vertical divider on the right side of the container is too wide. Should be 1px.

vertical-divider

**Comment by niklasros** [comment]
The '›' is positioned incorrect. It should be positioned between the Page and the tab page.

_Implementation_
search-netlify

_Figma_
search-figma

**Comment by niklasros** [comment]
_Collapsed_
On mobile, we don't want to show the vertical divider on the right side of the search container.

vertical-divider-1-mobile

_Expanded_
On mobile, we don't want to show the vertical divider on the left side of the search icon.

vertical-divider-2-mobile

**Comment by niklasros** [comment]
When pressing search on mobile, the entire website zooms in, which makes the search results hard to read.

search-expanded-1-mobile

search-expanded-2-mobile

**Comment by helloimela** [comment]
All feedback has been fixed @niklasros

**Comment by niklasros** [comment]
> When search is expanded, it would be great if the text field is active so that the user can start writing directly instead of having to click it again.

This still doesn't work for me (Safari, Firefox & Chrome on a Macbook). The hover state is visbile when hovering, but the cursor is still default and not pointing-hand so I cant click outside the search icon.

**Comment by helloimela** [comment]
> > When search is expanded, it would be great if the text field is active so that the user can start writing directly instead of having to click it again.
> 
> This still doesn't work for me (Safari, Firefox & Chrome on a Macbook). The hover state is visbile when hovering, but the cursor is still default and not pointing-hand so I cant click outside the search icon.

@niklasros  Try to hard-refresh on chrome (Cmd+Shift+R) or open the link in incognito in mobile and desktop browsers, it seems working on mine, so maybe it's cached.

**Comment by niklasros** [comment]
On mobile, you can not access the search results on the bottom of the page. When swiping down and releasing the finger from the screen, the position of the page automatically goes up to the top.

https://user-images.githubusercontent.com/59045455/105321764-2ce93580-5bc8-11eb-86cd-b4a5df73986f.mov

**Comment by niklasros** [comment]
> > > When search is expanded, it would be great if the text field is active so that the user can start writing directly instead of having to click it again.
> > 
> > 
> > This still doesn't work for me (Safari, Firefox & Chrome on a Macbook). The hover state is visbile when hovering, but the cursor is still default and not pointing-hand so I cant click outside the search icon.
> 
> @niklasros Try to hard-refresh on chrome (Cmd+Shift+R) or open the link in incognito in mobile and desktop browsers, it seems working on mine, so maybe it's cached.

My bad, works good here as well!

**Comment by mmexvr** [comment]
Margin on the symbol when the search needs to be removed, margin was used before search was added

image

**Comment by mmexvr** [comment]
Should the whole list item be clickable or just the link text that is inside the list item? 

image

**Comment by niklasros** [comment]
> Should the whole list item be clickable or just the link text that is inside the list item?
> 
> image

It would be great if the entire list item is clickable.

**Comment by helloimela** [comment]
@niklasros @mmexvr Fixed has been added for the feedbacks
- Remove margin on scania symbol that was added before search exist
- Fixed mobile scrolling on search result
- Click on entire list

**Review by niklasros — APPROVED** [review]
Looks great!

**Pull request merged**
