### PR TITLE
updated content for side menu

### PR DESCRIPTION
**Pull request by gaonita**
**This is now the release candidate!** 

**Describe pull-request**  
content updated 
- Side menu: added **Responsive** column and documentation in the code section

**Solving issue**  
Fixes: [AB#1220](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1220)

**How to test**  
I fetched the latest CMS data so it includes updates that @matyldamc @charlottelorensson or @mmexvr made. Feel free to check your changes here!

### CODE REVIEW

**Review by matyldamc — APPROVED** [review]

**Review by theJohnnyMe — APPROVED** [review]

**Comment by theJohnnyMe** [comment]
Looks good to me.

**Review by mmexvr — APPROVED** [review]

**Comment by mmexvr** [comment]
Looks good!

**Review by alexlioliopoulos — CHANGES_REQUESTED** [review]
There are several issues with some of the pages in the CMS, so please do not update yet. I will let you know when to re-update later today.

**Comment by alexlioliopoulos** [comment]
Also, there seems to be a weird colour change in our anchor links.

**New PR**
image

**Current**
image

Could you have a look and find out why? @gaonita @mmexvr

**Comment by mmexvr** [comment]
Should work now, can you confirm @alexlioliopoulos

**Comment by alexlioliopoulos** [comment]
Super!

**Review by alexlioliopoulos — APPROVED** [review]

**Pull request merged**
