### PR TITLE
Improvement/task 1621

### PR DESCRIPTION
**Pull request by albinscania**
**Describe pull-request**  
- Installed prettier for code-formatting
- Installed eslint (and configured rules) for linting
- Installed husky for pre-commit hooks
- prettier and eslint automatically runs on commit to avoid errors in committed code.

**Solving issue**  
_Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)_
Fixes: #1621
(also fixes 1622 and 1624)

**How to test**  
Check out the branch, do a commit. If that works fine, make an intended error (or mess up formatting), and retry. should fail :)

### CODE REVIEW

**Comment by areblk** [comment]
Not sure what steps to take to test this. I noticed that I was able to delete files, stage changes, commit and push via VS Code Source Control. I'm not able to do it like that for the /sdds repo. In there, I need to use the `npm run commit` script to set commit message.

When I reset my last commit and committed again, it seems like it merged from master by itself.

Now I don't know how to reset my commits and restore the files I deleted :-(

**Comment by areblk** [comment]
@albinscania could you give some examples of expected behaviour for correct and incorrect ways of committing? thanks!

**Comment by albinscania** [comment]
@areblk for now (since commitizen etc. is not done yet, that's another card) you can commit (with regular git commit -am ..., or through your tool of choice) with no special command (like npm run commit or similiar) as long as Prettier and Eslint won't complain about the code, which I guess they didn't do in your case because there were no errors introduced :) ?

But yeah, this might be a bit tricky to test, so maybe we can chill with it and talk about it on the dev-meeting tomorrow?

**Comment by areblk** [comment]
Some conflicts I noticed (i reset my commits)
- When running prettier-format, indentation is set to 2 blank spaces
image

- When saving a .ts||.js file in vs-code, indentation is set to 4 blank spaces. Seems like the prettier-format is being overwritten by script in `.vscode\settings.json`
image

**Comment by areblk** [comment]
prettier doesn't seem to run when committing thru CLI. Is it expected to run as if `npm run pre-commit`?

**Comment by theJohnnyMe** [comment]
> Some conflicts I noticed
> 
> * When running prettier-format, indentation is set to 2 blank spaces
>   image
> * When saving a .ts||.js file in vs-code, indentation is set to 4 blank spaces. Seems like the prettier-format is being overwritten by script in `.vscode\settings.json`
>   image

@albinscania  - I wonder if we can remove .vscode/settings.json file?

**Comment by areblk** [comment]
For the `npm run pre-commit`to run properly, I have to run `npm run eslint` first. Like it needs to be activated for the pre-commit to run the second argument. This is my log where you can see that it doesn't run checks on first time.

```
PS C:\dev\scania-digital-design-system\sdds-website-1> npm run pre-commit

> sdds-website@1.9.0 pre-commit
> npm run prettier-check && npm run eslint


> sdds-website@1.9.0 prettier-check
> prettier --check "src/**/*.{ts,js}"

Checking formatting...
[warn] src\testing-1621\commit-testing.js
[warn] src\testing-1621\eslist-testing.js
[warn] src\testing-1621\prettier-testing.ts
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
PS C:\dev\scania-digital-design-system\sdds-website-1> npm run prettier-format

> sdds-website@1.9.0 prettier-format
> prettier --write "src/**/*.{ts,js}"

src\app\app-routing.module.ts 93ms
src\app\app.component.spec.ts 25ms
src\app\app.component.ts 15ms
src\app\app.interface.ts 29ms
src\app\app.module.ts 11ms
src\app\app.pipe.ts 45ms
src\app\app.service.ts 56ms
src\app\components\card\card.component.ts 14ms
src\app\components\code-example\code-example.component.ts 8ms
src\app\components\code-example\code-snippet\code-snippet.component.ts 29ms
src\app\components\color-list\color-list.component.ts 38ms
src\app\components\content-header\content-header.component.ts 11ms
src\app\components\cookies-message\cookies-message.component.ts 18ms
src\app\components\footer\footer.component.ts 10ms
src\app\components\header\header.component.ts 28ms
src\app\components\icon-list\icon-list.component.ts 82ms
src\app\components\main\main.component.ts 65ms
src\app\components\navigation\navigation.component.ts 24ms
src\app\components\new-icon-list\new-icon-list.component.ts 59ms
src\app\components\page\landing-page\landing-page.component.ts 11ms
src\app\components\page\page.component.ts 20ms
src\app\components\pictogram-list\pictogram-list.component.ts 47ms
src\app\components\search-list\search-list.component.ts 11ms
src\app\components\search-list\search.service.ts 72ms
src\app\components\statistics\statistics.component.ts 12ms
src\app\transloco-root.module.ts 9ms
src\environments\environment.prod.ts 5ms
src\environments\environment.ts 4ms
src\main.ts 5ms
src\polyfills.ts 7ms
src\test.ts 8ms
src\testing-1621\commit-testing.js 18ms
src\testing-1621\eslist-testing.js 4ms
src\testing-1621\prettier-testing.js 5ms
src\testing-1621\prettier-testing.ts 8ms
PS C:\dev\scania-digital-design-system\sdds-website-1> npm run eslint

> sdds-website@1.9.0 eslint
> eslint ./src --ext .js,.ts


C:\dev\scania-digital-design-system\sdds-website-1\src\testing-1621\commit-testing.js
  1:1  error  'foo' is not defined                         no-undef
  2:3  error  'reallyLongArg' is not defined               no-undef
  3:3  error  'omgSoManyParameters' is not defined         no-undef
  4:3  error  'IShouldRefactorThis' is not defined         no-undef
  5:3  error  'isThereSeriouslyAnotherOne' is not defined  no-undef

  1:1  error  'foo' is not defined                         no-undef
  2:3  error  'reallyLongArg' is not defined               no-undef
  3:3  error  'omgSoManyParameters' is not defined         no-undef
  4:3  error  'IShouldRefactorThis' is not defined         no-undef
  5:3  error  'isThereSeriouslyAnotherOne' is not defined  no-undef

C:\dev\scania-digital-design-system\sdds-website-1\src\testing-1621\prettier-testing.ts
  7:14  warning  'arg0' is defined but never used  @typescript-eslint/no-unused-vars
  7:25  warning  'arg1' is defined but never used  @typescript-eslint/no-unused-vars
  7:36  warning  'arg2' is defined but never used  @typescript-eslint/no-unused-vars
  7:47  warning  'arg3' is defined but never used  @typescript-eslint/no-unused-vars

✖ 14 problems (10 errors, 4 warnings)

PS C:\dev\scania-digital-design-system\sdds-website-1> npm run pre-commit

> sdds-website@1.9.0 pre-commit
> npm run prettier-check && npm run eslint


> sdds-website@1.9.0 prettier-check
> prettier --check "src/**/*.{ts,js}"

Checking formatting...
All matched files use Prettier code style!

> sdds-website@1.9.0 eslint
> eslint ./src --ext .js,.ts


C:\dev\scania-digital-design-system\sdds-website-1\src\testing-1621\commit-testing.js
  1:1  error  'foo' is not defined                         no-undef
  2:3  error  'reallyLongArg' is not defined               no-undef
  3:3  error  'omgSoManyParameters' is not defined         no-undef
  4:3  error  'IShouldRefactorThis' is not defined         no-undef
  5:3  error  'isThereSeriouslyAnotherOne' is not defined  no-undef

C:\dev\scania-digital-design-system\sdds-website-1\src\testing-1621\prettier-testing.js
  1:1  error  'foo' is not defined                         no-undef
  2:3  error  'reallyLongArg' is not defined               no-undef
  3:3  error  'omgSoManyParameters' is not defined         no-undef
  4:3  error  'IShouldRefactorThis' is not defined         no-undef
  5:3  error  'isThereSeriouslyAnotherOne' is not defined  no-undef

C:\dev\scania-digital-design-system\sdds-website-1\src\testing-1621\prettier-testing.ts
  7:14  warning  'arg0' is defined but never used  @typescript-eslint/no-unused-vars
  7:25  warning  'arg1' is defined but never used  @typescript-eslint/no-unused-vars
  7:36  warning  'arg2' is defined but never used  @typescript-eslint/no-unused-vars
  7:47  warning  'arg3' is defined but never used  @typescript-eslint/no-unused-vars

✖ 14 problems (10 errors, 4 warnings)

PS C:\dev\scania-digital-design-system\sdds-website-1>

**Review by theJohnnyMe — APPROVED** [review]
Test OK

**Review by areblk — APPROVED** [review]
OK

**Comment by theJohnnyMe** [comment]
Looks good to me.

**Pull request merged**
