### PR TITLE
Improvement/task 1623

### PR DESCRIPTION
**Pull request by albinscania**
**Describe pull-request**  
Installed and added commitizen and commitlint to force nice commit-messages!

**Solving issue**  
_Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)_
Fixes: #1623

**How to test**  
add a cool file and try to do a commit! didn't write a compliant message? no soup for you!
... or run "npm run commit" and answer the questions truthfully, and hopefully everything works!

### CODE REVIEW

**Review by theJohnnyMe — APPROVED** [review]
Checked and tested OK, both commitlint and commitizen. Nice work Albin!

**Comment by areblk** [comment]
Was able to run install and commit, but commit runs before prettier - so I wasn't able to commit even though I followed the rules (I think...). I think prettier should run prior to committizen, so we don't have to walk through the guide if prettier will fail. Here's a log.

Also, weird that there are so many files not compliant although they could be checked and formatted prior to previous merge.

```
PS C:\dev\scania-digital-design-system\sdds-website> npm run commit

> sdds-website@1.9.0 commit
> cz

cz-cli@4.2.4, cz-conventional-changelog@3.3.0

? Select the type of change that you're committing: ci:       Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
? What is the scope of this change (e.g. component or file name): (press enter to skip) committizen-testing
? Write a short, imperative tense description of the change (max 75 chars):
 (7) testing
? Provide a longer description of the change: (press enter to skip)

? Are there any breaking changes? No
? Does this change affect any open issues? Yes
? If issues are closed, the commit requires a body. Please enter a longer description of the commit itself:
 lkaslkjaslkjd aslkja askdj
? Add issue references (e.g. "fix #123", "re #123".):
 AB#1623

> sdds-website@1.9.0 pre-commit
> npm run prettier-check && npm run eslint


> sdds-website@1.9.0 prettier-check
> prettier --check "src/**/*.{ts,js}"

Checking formatting...
[warn] src\app\app-routing.module.ts
[warn] src\app\app.component.spec.ts
[warn] src\app\app.component.ts
[warn] src\app\app.interface.ts
[warn] src\app\app.module.ts
[warn] src\app\app.pipe.ts
[warn] src\app\app.service.ts
[warn] src\app\components\card\card.component.ts
[warn] src\app\components\code-example\code-example.component.ts
[warn] src\app\components\code-example\code-snippet\code-snippet.component.ts
[warn] src\app\components\color-list\color-list.component.ts
[warn] src\app\components\content-header\content-header.component.ts
[warn] src\app\components\cookies-message\cookies-message.component.ts
[warn] src\app\components\footer\footer.component.ts
[warn] src\app\components\header\header.component.ts
[warn] src\app\components\icon-list\icon-list.component.ts
[warn] src\app\components\main\main.component.ts
[warn] src\app\components\navigation\navigation.component.ts
[warn] src\app\components\new-icon-list\new-icon-list.component.ts
[warn] src\app\components\page\landing-page\landing-page.component.ts
[warn] src\app\components\page\page.component.ts
[warn] src\app\components\page\tab-content\tab-content.component.ts
[warn] src\app\components\pictogram-list\pictogram-list.component.ts
[warn] src\app\components\search-list\search-list.component.ts
[warn] src\app\components\search-list\search.service.ts
[warn] src\app\components\statistics\statistics.component.ts
[warn] src\app\transloco-root.module.ts
[warn] src\environments\environment.prod.ts
[warn] src\environments\environment.ts
[warn] src\main.ts
[warn] src\polyfills.ts
[warn] src\test.ts
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
husky - pre-commit hook exited with code 1 (error)
git exited with error code 1
PS C:\dev\scania-digital-design-system\sdds-website>

**Comment by areblk** [comment]
All those files changing was due to windows/mac thing with the end of line. I changed my .gitconfig and it solved that problem. Other comments still valid.

**Review by areblk — APPROVED** [review]
As a final test, I committed thru CLI with incorrect message format and it failed as expected, with a clear error message! Finally, i committed thru CLI with correct format message and i was able to commit and push.

Nice work!

**Review by gaonita — APPROVED** [review]
tested with random stuff to commit, no soup for me indeed :D

**Pull request merged**
